# @package _global_

defaults:
  - override /solver: tension_modulated
  - override /hydra/launcher: joblib

ic_generator_name: Gaussian
name: ftm_string_lin_${number_ics}_${ic_generator_name}_${solver.sampling_rate}Hz

number_ics: 1000
ic_params:
  ic_max_amplitude: 0.01
  ic_min_amplitude: 0.001
  ic_amplitude_random: True
  ic_type: pluck

solver:
  sampling_rate: 16000
  use_nonlinear: False
  final_time: 1.0

ic_generator:
  _target_: physmodjax.solver.generator.${ic_generator_name}
  num_points: ${solver.n_gridpoints}

scratch_dir: "."
output_dir: ${scratch_dir}/data/${name}

hydra:
  run:
    dir: ${output_dir}
  job:
    chdir: True
  sweep:
    dir: ${scratch_dir}/data/ftm_linear
    subdir: ${name}
  sweeper:
    params:
      solver: '{sampling_rate: 4000, n_max_modes: 10}, {sampling_rate: 16000, n_max_modes: 25}'
      ic_generator_name: Gaussian, Noise
  launcher:
    n_jobs: 1