_target_: physmodjax.models.autoencoders.BatchedKoopmanAutoencoder1D
_partial_: True
d_vars: 2
d_model: 101
norm: "layer"
encoder_model:
  _target_: flax.linen.Dense
  _partial_: True
  features: 256 # 128 * 2
  kernel_init:
    _target_: flax.linen.initializers.orthogonal
  use_bias: False
decoder_model:
  _target_: flax.linen.Dense
  _partial_: True
  features: "${eval:'${..d_vars} * ${..d_model}'}"
  kernel_init: 
    _target_: flax.linen.initializers.orthogonal
  use_bias: False
dynamics_model:
  _target_: physmodjax.models.recurrent.LRUDynamicsVarying
  _partial_: True
  d_hidden: 128 # complex
  r_min: 0.99
  r_max: 1.0
  max_phase: 6.28
  clip_eigs: False
  model:
    _target_: physmodjax.models.mlp.MLP
    hidden_channels: [128, 128, 128, 256]