_target_: physmodjax.models.fno.BatchedFNO1D
_partial_: True
n_modes: 20 # around half of the number of grid points
hidden_channels: 8
d_vars: 2 # position and velocity
n_layers: 4
norm: "layer"
training: True