_target_: physmodjax.models.autoencoders.BatchedKoopmanAutoencoder1D
_partial_: True
d_vars: 2
d_model: 101
norm: "layer"
encoder_model:
  _target_: physmodjax.models.mlp.MLP
  _partial_: True
  hidden_channels: [128, 128, 256]
  kernel_init:
    _target_: flax.linen.initializers.orthogonal
decoder_model:
  _target_: physmodjax.models.mlp.MLP
  _partial_: True
  hidden_channels: [128, 128, "${eval:'${...d_vars} * ${...d_model}'}"]
  kernel_init: 
    _target_: flax.linen.initializers.orthogonal
dynamics_model:
  _target_: physmodjax.models.recurrent.LRUDynamics
  _partial_: True
  d_hidden: 128 # complex
  r_min: 0.99
  r_max: 0.999
  max_phase: 6.28
  clip_eigs: True