_target_: physmodjax.models.ssm.BatchStackedSSMModel
_partial_: True
training: True
norm: "batch"
activation: "gelu"
d_model: 101
d_vars: 2
n_layers: 4
ssm_first_layer: 
  _target_: physmodjax.models.ssm.S5SSM
  _partial_: True
  d_hidden: 128
ssm:
  _target_: physmodjax.models.ssm.S5SSM
  _partial_: True
  d_hidden: 128
