_target_: physmodjax.models.autoencoders.BatchedKoopmanAutoencoder2D
_partial_: True
d_latent_channels: 32
d_latent_dims: [5, 5]
norm: "batch"
encoder_model:
  _target_: physmodjax.models.conv.ConvEncoder
  _partial_: True
  block_size: [8, 16, 32]
decoder_model:
  _target_: physmodjax.models.conv.ConvDecoder
  _partial_: True
  block_size: [8, 16, 32]
  output_features: 3
dynamics_model:
  _target_: physmodjax.models.recurrent.LRUDynamicsVarying
  _partial_: True
  d_hidden: 400 # 800 reals 5*5*32 = 400 complex
  r_min: 0.99
  r_max: 1.0
  max_phase: 6.28
  model:
    _target_: physmodjax.models.mlp.MLP
    hidden_channels: [400, 400, 800]