_target_: physmodjax.models.autoencoders.BatchedDenseKoopmanAutoencoder2D
_partial_: True
d_vars: 2
d_model: [41, 37]
norm: "layer"
encoder_model:
  _target_: flax.linen.Dense
  _partial_: True
  features: 4096
  kernel_init:
    _target_: flax.linen.initializers.orthogonal
  use_bias: False
decoder_model:
  _target_: flax.linen.Dense
  _partial_: True
  features: "${eval:'${..d_vars} * ${..d_model[0]} * ${..d_model[1]}'}"
  kernel_init:
    _target_: flax.linen.initializers.orthogonal
  use_bias: False
dynamics_model:
  _target_: physmodjax.models.recurrent.LRUDynamicsVarying
  _partial_: True
  d_hidden: 2048 # complex
  r_min: 0.0001
  r_max: 0.9999
  max_phase: 6.28
  clip_eigs: False
  model:
    _target_: physmodjax.models.mlp.MLP
    hidden_channels: [512, 1024, 2048, 4096]
    layer_norm: False