_target_: physmodjax.models.ssm.BatchStackedSSM2DModel
_partial_: True
d_model: [41, 37]
norm: "layer"
activation: "gelu" # important otherwise parameters grow too large
d_vars: 2
n_layers: 4
ssm_first_layer: 
  _target_: physmodjax.models.ssm.LRU
  _partial_: True
  r_min: 0.001
  r_max: 0.999
  d_hidden: 512
ssm:
  _target_: physmodjax.models.ssm.LRU
  _partial_: True
  r_min: 0.001
  r_max: 0.999
  d_hidden: 512