# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/solver/wave1d_solver_tensionmodulated.ipynb.

# %% auto 0
__all__ = [
    "nonlinear_string_func",
    "nl_harmonic_oscillator",
    "nl_harmonic_oscillator_diffrax",
    "Wave1DSolverNL",
]

# %% ../../nbs/solver/wave1d_solver_tensionmodulated.ipynb 6
import numpy as np
from scipy.integrate import solve_ivp
from physmodjax.utils.ftm import (
    forward_STL,
    inverse_STL,
    eigenvalues_from_pde,
    string_eigenvalues_sqrt,
    string_eigenfunctions,
    StringParameters,
)
from numba import jit, njit
from functools import partial
from einops import rearrange
import diffrax as drx
import jax.numpy as jnp
from jax.typing import ArrayLike


# %% ../../nbs/solver/wave1d_solver_tensionmodulated.ipynb 9
@njit
def nonlinear_string_func(
    t,  # time
    state,  # state vector
    n_max_modes,  # number of modes
    use_nonlinear,  # use nonlinear wave equation
    pre,  # precalculated constant
    H,  # H matrix
    H_1,  # H_1 matrix
    M_v,  # M_v matrix
    M_y,  # M_y matrix
) -> np.ndarray:  # state at timestep t and position x (u(x, t))
    # unpack the state vector
    y = state[:n_max_modes]  # displacement in modal coordinates
    v = state[n_max_modes:]  # velocity in modal coordinates

    # add axis for calculation
    y = y.reshape(-1, 1)

    # calculate the $\bar{b}$ vector
    if use_nonlinear:
        t_1 = pre * y.T @ H @ y
        b = t_1 * H_1 @ y

    # update the state vector
    v = v
    dv_dt = -M_v @ v - M_y @ y.reshape(-1)

    if use_nonlinear:
        dv_dt -= b.reshape(-1)

    # return the state derivatives
    return np.concatenate((v, dv_dt))


@njit
def nl_harmonic_oscillator(
    t,  # time
    state,  # state vector (state_vars,)
    n_max_modes,  # number of modes
    use_nonlinear,  # use nonlinear wave equation
    c,  # positive dampings
    k,  # stiffness
    mu,  # mu integers
    gamma,  # precalculated scalar constant times squared wavenumbers
) -> np.ndarray:  # state at timestep t and position x (u(x, t))
    # unpack the state vector
    y = state[:n_max_modes]  # displacement in modal coordinates
    v = state[n_max_modes:]  # velocity in modal coordinates

    # update the state vector
    dy_dt = v
    dv_dt = -c * v - k * y

    if use_nonlinear:
        # calculate the $\bar{b}$ vector and subtract it from the acceleration
        energy = np.sum(mu**2 * y**2)
        b = gamma * energy * y
        dv_dt -= b

    # return the state derivatives
    return np.concatenate((dy_dt, dv_dt))


def nl_harmonic_oscillator_diffrax(
    t,  # time
    state,  # state vector (state_vars,)
    args,  # additional arguments
    n_max_modes,  # number of modes
    use_nonlinear,  # use nonlinear wave equation
    c,  # positive dampings
    k,  # stiffness
    mu,  # mu integers
    gamma,  # precalculated scalar constant times squared wavenumbers
) -> ArrayLike:  # state at timestep t and position x (u(x, t))
    # unpack the state vector
    y = state[:n_max_modes]  # displacement in modal coordinates
    v = state[n_max_modes:]  # velocity in modal coordinates

    # update the state vector
    dy_dt = v
    dv_dt = -c * v - k * y

    if use_nonlinear:
        # calculate the $\bar{b}$ vector and subtract it from the acceleration
        energy = jnp.sum(mu**2 * y**2)
        b = gamma * energy * y
        dv_dt -= b

    # return the state derivatives
    return jnp.concatenate((dy_dt, dv_dt))


# %% ../../nbs/solver/wave1d_solver_tensionmodulated.ipynb 11
class Wave1DSolverNL:
    # fmt: off
    def __init__(
        self,
        string_parameters: StringParameters,  # Physical parameters of the string
        sampling_rate: int = 48000,  # 1/s     Temporal sampling frequency
        final_time: float = 0.5,     # s       Duration of the simulation
        n_gridpoints: int = 101,     # pts/m   Spatial sampling grid
        n_max_modes: int = 99,       #         Number of modal expansion terms
        use_nonlinear: bool = True,  #         Use nonlinear wave equation
        method: str = "DOP853",      #         Integration method
        rtol: float = 1e-12,         #         Relative tolerance
        atol: float = 1e-14,         #         Absolute tolerance
        use_diffrax: bool = False,   #         Use diffrax for integration
    ):
    # fmt: on

        self.sampling_rate = sampling_rate
        self.final_time = final_time
        self.n_gridpoints = n_gridpoints
        self.n_max_modes = n_max_modes
        self.use_nonlinear = use_nonlinear
        self.method = method
        self.rtol = rtol
        self.atol = atol
        self.string_parameters = string_parameters
        self.use_diffrax = use_diffrax
        
        self.wavenumbers = string_eigenvalues_sqrt(
            n_max_modes,
            string_parameters.length,
        )
        self.grid = np.linspace(0, string_parameters.length, n_gridpoints)
        self.dx = self.grid[1] - self.grid[0]
        self.K = string_eigenfunctions(
            wavenumbers=self.wavenumbers,
            grid=self.grid,
        )
        self.mu = np.arange(1, self.n_max_modes + 1, dtype=np.float64)
        self.eigvals = eigenvalues_from_pde(string_parameters, self.wavenumbers)
        self.c = -2 * np.real(self.eigvals)
        self.k = self.eigvals.imag**2 + self.eigvals.real**2
        
        #  temporal grid use arange to make sure that the timestep corresponds exactly to the sampling frequency
        self.dt = 1 / self.sampling_rate  # s     temporal sampling interval
        self.timesteps = np.arange(0, self.final_time, self.dt)

    def solve_modal(
            self,
            bar_u0,
            bar_v0,
        ) -> tuple[np.ndarray, np.ndarray]:
        
        if not self.use_diffrax:
            # solve the wave equation in modal coordinates
            sol = solve_ivp(
                fun=partial(
                    nl_harmonic_oscillator,
                    n_max_modes=self.n_max_modes,
                    use_nonlinear=self.use_nonlinear,
                    mu=self.mu,
                    gamma=self.wavenumbers**2 \
                        / self.string_parameters.area_density \
                        * self.string_parameters.E \
                        * self.string_parameters.A \
                        * np.pi**2 \
                        / self.string_parameters.length**4,
                    c=self.c,
                    k=self.k,
                ),
                t_span=[0, self.final_time],
                y0=np.concatenate([bar_u0, bar_v0], axis=0),
                t_eval=self.timesteps,
                method=self.method,
                rtol=self.rtol,
                atol=self.atol,
            )

            # unpack the solution
            bar_u = sol.y[: self.n_max_modes]
            bar_v = sol.y[self.n_max_modes :]
            t = sol.t
        else:
            term = drx.ODETerm(
                partial(
                    nl_harmonic_oscillator_diffrax,
                    n_max_modes=self.n_max_modes,
                    use_nonlinear=self.use_nonlinear,
                    mu=self.mu,
                    gamma=self.wavenumbers**2 \
                        / self.string_parameters.area_density \
                        * self.string_parameters.E \
                        * self.string_parameters.A \
                        * np.pi**2 \
                        / self.string_parameters.length**4,
                    c=self.c,
                    k=self.k,
                )
            )

            solver = drx.Dopri8()  # RK45
            sol: drx.Solution = drx.diffeqsolve(
                term,
                solver,
                t0=0.0,
                dt0=self.dt,
                t1=self.final_time,
                y0=jnp.concatenate([bar_u0, bar_v0], axis=0),
                saveat=drx.SaveAt(ts=self.timesteps),
                max_steps=self.sampling_rate * 2,
            )

            # unpack the solution
            bar_u = sol.ys[:, : self.n_max_modes].T # (n_modes, n_timesteps)
            bar_v = sol.ys[:, self.n_max_modes :].T # (n_modes, n_timesteps)
            t = sol.ts

        return t, bar_u, bar_v


    def solve(
        self,
        u0: np.ndarray = None,  # initial displacement (default: None)
        v0: np.ndarray = None,  # initial velocity (default: None)
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        # set the initial conditions if not given
        u0 = u0 if u0 is not None else np.zeros_like(self.grid)
        v0 = v0 if v0 is not None else np.zeros_like(self.grid)

        # enforce the dirichlet boundary conditions
        # TODO: this should be in the IC itself
        u0[0] = 0
        u0[-1] = 0
        v0[0] = 0
        v0[-1] = 0

        # transform the initial conditions to modal coordinates
        bar_u0 = forward_STL(self.K, u0, self.dx)
        bar_v0 = forward_STL(self.K, v0, self.dx)

        t, bar_u, bar_v = self.solve_modal(
            bar_u0,
            bar_v0,
        )

        # transform back to the physical domain
        u = inverse_STL(self.K, bar_u, self.string_parameters.length)
        v = inverse_STL(self.K, bar_v, self.string_parameters.length)

        return (
            t,
            rearrange(u, "g t -> t g"),
            rearrange(v, "g t -> t g"),
        )
