# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/utils/checkpoint.ipynb.

# %% auto 0
__all__ = [
    "restore_experiment_state",
    "download_ckpt_single_run",
    "restore_run_from_wandb",
    "fix_prepend_ones",
    "get_config_single_run",
]

# %% ../../nbs/utils/checkpoint.ipynb 2
from pathlib import Path
from typing import Any

import flax.linen as nn
import hydra
import jax
import orbax.checkpoint as obc
import wandb
from flax.training import train_state
from omegaconf import OmegaConf, DictConfig
from wandb.apis import public
import numpy as np


# %% ../../nbs/utils/checkpoint.ipynb 3
def restore_experiment_state(
    run_path: Path,  # Path to the run directory (e.g. "outputs/2024-01-23/22-15-11")
    best: bool = True,  # If True, restore the best checkpoint instead of the latest
    best_metric: str = "val/mae_rel",  # Metric to use for best checkpoint selection
    step_to_restore: int = None,  # If not None, restore the checkpoint at this step, incompatible with `best`
    kwargs: dict = {},  # Additional arguments to pass to the model
    device: jax.Device = None,  # Device to restore the model on
) -> tuple[train_state.TrainState, nn.Module, obc.CheckpointManager]:
    """
    Restores the train state from a run.

    Args:
        run_path (Path): Path to the run directory (e.g. "outputs/2024-01-23/22-15-11")
        best (bool): If True, restore the best checkpoint instead of the latest
        step_to_restore (int): If not None, restore the checkpoint at this step
        kwargs (dict): Additional arguments to pass to the model
        device (jax.Device): Device to restore the model on

    Returns:
    -------
        train_state.TrainState: The train state of the experiment
        nn.Module: The model used in the experiment
        CheckpointManager: The checkpoint manager
    """

    # Make sure the path is a Path object
    run_path = Path(run_path)

    # These are hardcoded, do not change
    ckpt_path = run_path / "checkpoints"
    config_path = run_path / ".hydra" / "config.yaml"
    cfg = OmegaConf.load(config_path)

    # Check if either `best` or `step_to_restore` is set, but not both
    if best:
        if step_to_restore is not None:
            raise ValueError(
                "You cannot set both `best` and `step_to_restore`. Please choose one."
            )
        if best_metric is None:
            raise ValueError(
                "If `best=True`, you must provide a `best_metric` to determine the best checkpoint."
            )

    options = obc.CheckpointManagerOptions(
        max_to_keep=1,
        create=True,
        best_fn=lambda x: float(
            x[best_metric]
        ),  # Shouldn't be hardcoded here, not a problem atm because we only save one step, best
        best_mode="min",
    )

    def set_restore_type(x: Any) -> obc.RestoreArgs:
        return obc.RestoreArgs(restore_type=np.ndarray)

    with obc.CheckpointManager(
        ckpt_path,
        options=options,
        item_handlers={
            "state": obc.PyTreeCheckpointHandler(),
            "default": obc.PyTreeCheckpointHandler(),
        },
    ) as checkpoint_manager:
        model_cls: nn.Module = hydra.utils.instantiate(cfg.model)
        model = model_cls(training=False, **kwargs)

        # Get checkpoint metadata
        step = (
            checkpoint_manager.latest_step()
            if not best
            else checkpoint_manager.best_step()
        )
        step = step_to_restore if step_to_restore is not None else step
        metadatas = checkpoint_manager.item_metadata(step)
        print(f"Restoring checkpoint from step {step}...")

        # Restore the metadata

        # Backwards compatibility for older checkpoints
        if "state" in metadatas and metadatas.state is not None:
            restore_args_state = jax.tree_util.tree_map(
                set_restore_type, metadatas["state"]
            )
            metadatas = checkpoint_manager.restore(
                step=step,
                args=obc.args.Composite(
                    state=obc.args.PyTreeRestore(
                        item=metadatas["state"],
                        restore_args=restore_args_state,
                    ),
                ),
            )
            metadata_state = metadatas.state

        elif "default" in metadatas and metadatas.default is not None:
            print("This is a checkpoint with old formatting")
            if "model" not in metadatas.default:
                raise ValueError("No model found in the checkpoint")

            restore_args_default = jax.tree_util.tree_map(
                set_restore_type, metadatas["default"]
            )
            metadatas = checkpoint_manager.restore(
                step=step,
                args=obc.args.Composite(
                    default=obc.args.PyTreeRestore(
                        item=metadatas["default"],
                        restore_args=restore_args_default,
                    ),
                ),
            )
            metadata_state = metadatas.default["model"]
        else:
            raise ValueError("No state found in the checkpoint")

        if "batch_stats" in metadata_state:
            # Define TrainState with optional batch_stats
            class TrainState(train_state.TrainState):
                key: jax.Array
                batch_stats: Any = None  # Optional field

            # Initialize the empty state
            state = TrainState(
                key={},
                step=0,
                apply_fn=model.apply,
                params=metadata_state["params"],
                tx={},
                opt_state=metadata_state["opt_state"],
                batch_stats=metadata_state["batch_stats"],
            )
        else:
            # Define TrainState with optional batch_stats
            class TrainState(train_state.TrainState):
                key: jax.Array

            state = TrainState(
                key={},
                step=0,
                apply_fn=model.apply,
                params=metadata_state["params"],
                tx={},
                opt_state=metadata_state["opt_state"],
            )

        # If device is not specified, use the default device
        if device is None:
            device = jax.devices()[0]
        # Move the state to the specified device
        state = jax.device_put(state, device)

        return state, model, checkpoint_manager


# %% ../../nbs/utils/checkpoint.ipynb 4
def download_ckpt_single_run(
    run_name: str,
    project: str = "iir-modal/physmodjax",
    tmp_dir: Path = Path("/tmp/physmodjax"),
    overwrite: bool = False,
) -> tuple[Path, DictConfig]:
    filter_dict = {
        "display_name": run_name,
    }

    # if wandb.run is None:
    # wandb.init()

    api: public.Api = wandb.Api()

    runs: public.Runs = api.runs(project, filter_dict)

    assert len(runs) > 0, f"No runs found with name {run_name}"
    assert len(runs) == 1, f"More than one run found with name {run_name}"

    run: public.Run = runs[0]
    conf = OmegaConf.create(run.config)

    artifacts: public.RunArtifacts = run.logged_artifacts()

    artifact: wandb.Artifact

    # check if no artifacts
    if len(artifacts) == 0:
        raise ValueError(f"No artifacts found for run {run_name}")

    for artifact in artifacts:
        if artifact.type == "model":
            checkpoint_path = tmp_dir / artifact.name
            if checkpoint_path.exists() and not overwrite:
                print(f"Checkpoint already exists at {checkpoint_path}, skipping")
                return checkpoint_path, conf
            else:
                artifact.download(checkpoint_path)

    # save config next to checkpoint
    conf_path = checkpoint_path / ".hydra" / "config.yaml"
    conf_path.parent.mkdir(parents=True, exist_ok=True)
    OmegaConf.save(conf, conf_path)

    print(f"Downloaded checkpoint to {checkpoint_path}")
    return checkpoint_path, conf


# %% ../../nbs/utils/checkpoint.ipynb 5
def restore_run_from_wandb(
    run_name: str,  # Name of the run to restore
    wandb_project: str,  # Name of the project on wandb
    device: jax.Device = None,  # Device to restore the model on
) -> tuple[train_state.TrainState, nn.Module, DictConfig]:
    """
    Restores the train state from a wandb run.

    Assumes that we want the model with the best checkpoint according to the metric in the config, or latest step.
    Assumes that we want to initialize the model with an output length equal to the number of steps used in training.
    """

    # Download the checkpoint and config from wandb
    checkpoint_path, cfg = download_ckpt_single_run(run_name, wandb_project)

    kwargs = {"n_steps": cfg.datamodule.num_steps_train[1]}
    if (
        hasattr(cfg, "checkpoint_manager_options")
        and hasattr(cfg.checkpoint_manager_options, "best_fn")
        and hasattr(cfg.checkpoint_manager_options.best_fn, "metric")
    ):
        print(
            f"Restoring best checkpoint according to metric {cfg.checkpoint_manager_options.best_fn.metric}"
        )
        best_metric = cfg.checkpoint_manager_options.best_fn.metric
        best = True
    else:
        print("Restoring latest checkpoint")
        best_metric = None
        best = False

    # Restore the checkpoint
    state, model, _ = restore_experiment_state(
        checkpoint_path,
        best=best,
        best_metric=best_metric,
        kwargs=kwargs,
        device=device,
    )

    return state, model, cfg


# %% ../../nbs/utils/checkpoint.ipynb 11
def fix_prepend_ones(
    run_name: str,
    wandb_project: str,
):
    checkpoint_path, conf = download_ckpt_single_run(run_name, project=wandb_project)
    # if conf.model.dynamics_model.model exists but there is no prepend-ones key, add it.
    if hasattr(conf.model, "dynamics_model"):
        if hasattr(conf.model.dynamics_model, "model"):
            if hasattr(conf.model.dynamics_model.model, "prepend_ones"):
                print(f"Model {run_name} has prepend_ones in the wrong place")
                del conf.model.dynamics_model.model.prepend_ones
        if not hasattr(conf.model.dynamics_model, "prepend_ones"):
            print(f"Model {run_name} has no prepend_ones")
            conf.model.dynamics_model.prepend_ones = False
    # Save config updated
    conf_path = checkpoint_path / ".hydra" / "config.yaml"
    conf_path.parent.mkdir(parents=True, exist_ok=True)
    OmegaConf.save(conf, conf_path)
    return conf


# %% ../../nbs/utils/checkpoint.ipynb 12
def get_config_single_run(
    run_name: str,  # Name of the run to restore
    project: str,  # Name of the project on wandb
) -> DictConfig:
    """
    Retrieves the configuration of a single run from WandB.
    """
    filter_dict = {
        "display_name": run_name,
    }

    api: public.Api = wandb.Api()

    runs: public.Runs = api.runs(project, filter_dict)

    if len(runs) == 0:
        raise ValueError(f"No runs found with name {run_name}")
    if len(runs) > 1:
        raise ValueError(f"More than one run found with name {run_name}")

    run: public.Run = runs[0]
    conf = OmegaConf.create(run.config)
    return conf
