_target_: physmodjax.utils.data.DirectoryDataModule
split: [0.8, 0.1, 0.1]
batch_size: 50
extract_channels: [0]
total_num_train: 1000
total_num_val: 1000
total_num_test: 1000
num_steps_train: [1, 999]
num_steps_val: [1, 999]
mode: "split"
standardize_dataset: True
windowed: False
cache: True
