_target_: physmodjax.utils.data.DirectoryDataModule
split: [0.8, 0.1, 0.1]
batch_size: 50
extract_channels: [0]
total_num_train: 4000
total_num_val: 4000
total_num_test: 4000
num_steps_train: [1, 3999]
num_steps_val: [1, 3999]
mode: "split"
standardize_dataset: True
windowed: False
cache: True
